language: java
matrix:
  include:
    - jdk: oraclejdk8
      env: TARGET=hikaricp
      env: OPTS=-P coverage
    - jdk: openjdk6
      env: TARGET=hikaricp-java6
      env: OPTS=

script: "mvn install -pl $TARGET $OPTS"
