language: java
jdk:
  - oraclejdk8
  - openjdk6

matrix:
  include:
    - jdk: oraclejdk8
      env: TARGET=hikaricp
    - jdk: openjdk6
      env: TARGET=hikaricp-java6

install:

script:
  - if [ "$TARGET" = "hikaricp" ]; then mvn install -DskipTests -Dmaven.javadoc.skip=true -V -pl $TARGET -P coverage; fi"
  - if [ "$TARGET" == "hikaricp-java6" ]; then mvn install -DskipTests -Dmaven.javadoc.skip=true -V -pl $TARGET; fi"
