sudo: false
language: java

dist:
  - trusty

before_script:
  - if [[ "x$JDK" == *'x9'* ]]; then export MAVEN_SKIP_RC=true; fi

script:
  - export JDK8_HOME=$(jdk_switcher home oraclejdk8)
  - export JDK11_HOME=/usr/lib/jvm/java-11-oracle
  - test -d "${JDK11_HOME}" || export JDK11_HOME=$(jdk_switcher home oraclejdk8)

before_cache:
  # No sense in caching current build artifacts
  - rm -rf $HOME/.m2/repository/com/zaxxer

cache:
  directories:
    - $HOME/.m2/repository

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk11
      env:
        - JDK=11

install: /bin/true

script:
  - mvn package -Dmaven.javadoc.skip=true -V -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
