language: java
sudo: false
cache:
  directories:
    - $HOME/.m2/repository
jdk:
  - oraclejdk8

install: rm -rf /home/travis/.m2/repository/*

script:
  - mvn install -Dmaven.javadoc.skip=true -V -B
  - jdk_switcher use openjdk7
  - mvn test
