language: java
sudo: false
cache:
  directories:
    - $HOME/.m2/repository
jdk:
  - oraclejdk8

install: /bin/true

script:
  - mvn install -Dskip.unit.tests=true -Dmaven.javadoc.skip=true -V -B
  - mvn clean test coveralls:report -V -pl hikaricp -P coverage
  - jdk_switcher use openjdk6
  - mvn test -pl hikaricp-java6 -Dmaven.exec.skip=true -V
